# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23409a1977fadb9a1fc5b6881b32c76eceb680fa01b2f01c2759f53d2d71b89c73d42ac5acc1996a53e0f423b8700e1245b324c93f7c6f4a51994222dbed304b

test:
  secret_key_base: 517b934ac4b6f1bbd5a9912efc623e36177b29d2a66463eea06b6d80dc992c3312ae6bf7ae457ac42edafee3449934a8c5d4932f07d1e9e4de0f3d2fc9094f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
